/**
 * Every riwaya entry point (src/hafs.ts, ...) is generated by scripts/generate-entries.ts.
 * This checks that each generated wrapper gives the same result as the core function
 * called with that riwaya's data.
 */
import * as core from "../src"
import * as bazzi from "../src/bazzi"
import * as douri from "../src/douri"
import * as hafs from "../src/hafs"
import * as qalun from "../src/qalun"
import * as qunbul from "../src/qunbul"
import * as shuba from "../src/shuba"
import * as sousi from "../src/sousi"
import * as warsh from "../src/warsh"
import { getListsOfRiwaya } from "../src/lists"
import type { RiwayaData } from "../src/lists/types"

type AnyFn = (...args: unknown[]) => unknown

/** Sample arguments (without the trailing data argument) and what the core function binds */
const samples: Record<string, [args: unknown[], bind: "lists" | "meta"]> = {
  getList: [["page"], "lists"],
  getListNormalised: [["juz"], "lists"],
  generatePartBlocks: [["manzil"], "lists"],
  ayahStringSplitter: [["2:255", true], "lists"],
  surahStringParser: [["18", false], "meta"],
  formatAyahId: [[262], "lists"],
  checkValidSurahAyah: [[2, 255], "lists"],
  checkValidSurahAyahPair: [[[2, 255]], "lists"],
  checkValidSurah: [[2], "meta"],
  checkValidAyahId: [[100], "meta"],
  checkValidPage: [[10], "meta"],
  checkValidJuz: [[3], "meta"],
  checkValidRuku: [[4], "meta"],
  checkValidManzil: [[5], "meta"],
  isValidSurah: [[115], "meta"],
  isValidAyahId: [[6300], "meta"],
  isValidSurahAyah: [[[2, 286]], "lists"],
  isValidPage: [[605], "meta"],
  isValidJuz: [[30], "meta"],
  isValidManzil: [[7], "meta"],
  isValidRuku: [[0], "meta"],
  isValidHizb: [[60], "meta"],
  isValidRubAlHizb: [[240], "lists"],
  getSurahMeta: [[3], "lists"],
  getSurahInfo: [[4], "lists"],
  getAyahCountInSurah: [[5], "lists"],
  findAyahIdBySurah: [[6, 7], "lists"],
  findSurahByAyahId: [[3000], "lists"],
  findSurahAyahByAyahId: [[3000], "lists"],
  getAyahMeta: [[4000], "lists"],
  getAyahMetasForSurah: [[112], "lists"],
  findJuz: [[18, 75], "lists"],
  findJuzByAyahId: [[2500], "lists"],
  getJuzMeta: [[15], "lists"],
  findJuzMetaBySurah: [[9, 93], "lists"],
  findJuzAndShift: [[9, 93], "lists"],
  findJuzAndShiftByAyahId: [[1300], "lists"],
  findPage: [[36, 1], "lists"],
  findPagebyAyahId: [[3706], "lists"],
  getPageMeta: [[300], "lists"],
  findManzil: [[17, 1], "lists"],
  findManzilByAyahId: [[2030], "lists"],
  getManzilMeta: [[4], "lists"],
  findRukuByAyahId: [[222], "lists"],
  getRukuMeta: [[100], "lists"],
  findRubAlHizb: [[2, 142], "lists"],
  findRubAlHizbByAyahId: [[149], "lists"],
  getRubAlHizbByAyahId: [[149], "lists"],
  getRubAlHizbMeta: [[120], "lists"],
  getRubAlHizbMetaByAyahId: [[5000], "lists"],
  findThumunAlHizb: [[2, 142], "lists"],
  findThumunAlHizbByAyahId: [[149], "lists"],
  getThumunAlHizbByAyahId: [[149], "lists"],
  getThumunAlHizbMeta: [[240], "lists"],
  getThumunAlHizbMetaByAyahId: [[5000], "lists"],
  findRangeAroundAyah: [[1000, "page"], "lists"],
  findRangeAroundSurahAyah: [[2, 255, "juz"], "lists"],
  getPartRange: [["ruku", 50], "lists"],
  isAyahJuzFirst: [[149], "lists"],
  isAyahPageFirst: [[8], "lists"],
  isSurahAyahJuzFirst: [[2, 142], "lists"],
  isSurahAyahPageFirst: [[2, 6], "lists"]
}

/** Generators are compared by what they yield */
const iterators: Record<string, unknown[]> = {
  ayahsInPart: ["page", 300],
  ayahsInPage: [600],
  ayahsInJuz: [29]
}

const entries = {
  Bazzi: bazzi,
  Douri: douri,
  Hafs: hafs,
  Qalun: qalun,
  Qunbul: qunbul,
  Shuba: shuba,
  Sousi: sousi,
  Warsh: warsh
}

describe.each(Object.entries(entries))("%s entry point wrappers", (name, entry) => {
  const data: RiwayaData = getListsOfRiwaya(name as keyof typeof entries)
  const exported: Record<string, unknown> = entry
  const coreFns = core as unknown as Record<string, AnyFn>

  const covered = new Set([
    ...Object.keys(samples),
    ...Object.keys(iterators),
    "convertAyahTo",
    "convertAyahSpanTo",
    "nextAyah",
    "prevAyah",
    // Re-exported unchanged, they take no riwaya data
    "getRubAlHizb",
    "isValidAyahNo",
    "string2NumberSplitter",
    "string2NumberSplitterStrict",
    "formatSurahAyah"
  ])

  test("every exported function has a sample in this test", () => {
    const fns = Object.keys(exported).filter((k) => typeof exported[k] === "function" && !/^create[A-Z]/.test(k))
    expect(fns.filter((k) => !covered.has(k))).toEqual([])
  })

  test.each(Object.entries(samples).filter(([fn]) => fn in exported))(
    "%s matches the core function",
    (fn, [args, bind]) => {
      const bound = bind === "lists" ? data : data.meta
      const wrapper = exported[fn] as AnyFn
      expect(wrapper(...args)).toEqual(coreFns[fn](...args, bound))
    }
  )

  test.each(Object.entries(iterators))("%s yields the same ayahs as the core function", (fn, args) => {
    const wrapper = exported[fn] as (...a: unknown[]) => Iterable<unknown>
    const coreFn = coreFns[fn] as (...a: unknown[]) => Iterable<unknown>
    expect([...wrapper(...args)]).toEqual([...coreFn(...args, data)])
  })

  test("nextAyah and prevAyah pass the options through", () => {
    for (const wrap of [true, false]) {
      expect(entry.nextAyah(114, 6, { wrap })).toEqual(core.nextAyah(114, 6, data, { wrap }))
      expect(entry.prevAyah(1, 1, { wrap })).toEqual(core.prevAyah(1, 1, data, { wrap }))
    }
    expect(entry.nextAyah(2, 5)).toEqual(core.nextAyah(2, 5, data))
    expect(entry.prevAyah(2, 5)).toEqual(core.prevAyah(2, 5, data))
  })

  test("convertAyahTo uses this riwaya as the source", () => {
    const convertTo = exported.convertAyahTo as AnyFn
    const spanTo = exported.convertAyahSpanTo as AnyFn
    expect(convertTo(2, 5, "Hafs")).toEqual(core.convertAyah(2, 5, name as never, "Hafs"))
    expect(spanTo(1, 1, "Warsh")).toEqual(core.convertAyahSpan(1, 1, name as never, "Warsh"))
  })

  test("list exports and meta come from this riwaya", () => {
    expect(exported.meta).toBe(data.meta)
    expect(exported.PageList).toBe(data.PageList)
    expect(exported.SurahList).toBe(data.SurahList)
    expect(exported[`${name}Lists`]).toBe(data)
  })
})
