/**
 * Surah names generator for the languages that come from the Quran.com API.
 *
 * Fetches https://api.quran.com/api/v4/chapters?language=<lang> and writes
 * src/i18n/surah.<lang>.ts as [transliteration, translated name] pairs. Quran.com has no
 * per-language transliterations, so the first element is its Latin `name_simple`
 * ("Al-Baqarah") in every language. For Malayalam, Quran.com gives the name in Malayalam
 * script instead of a translation.
 *
 * Two quirks of the data are repaired: Malay names carry trailing spaces and newlines, and
 * 15 Italian names have accented letters replaced by Cyrillic ones ("Al-Arтf" for
 * "Al-Arâf", a codepage mix-up). Generation fails if a name falls back to English or
 * contains letters outside the language's script, so new quirks do not slip through.
 *
 * Usage:
 *   pnpx jiti examples/data-check/generate-surah-names.ts [lang...] [--check]
 *
 *   (no langs)  every language below
 *   --check     compare against src/i18n/surah.<lang>.ts instead of writing it
 *
 * Examples:
 *   pnpx jiti examples/data-check/generate-surah-names.ts it ms
 *   pnpx jiti examples/data-check/generate-surah-names.ts --check
 */

import { execSync } from "node:child_process"
import { existsSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const i18nDir = join(here, "..", "..", "src", "i18n")
const scriptRef = "examples/data-check/generate-surah-names.ts"

interface LanguageConfig {
  /** Doc comment for the exported constant, when the pairs mean something else than usual */
  doc?: string
  /** Every letter of a translated name must be in this script */
  script: RegExp
}

const latin = /\p{Script=Latin}/u

const languages: Record<string, LanguageConfig> = {
  bn: { script: /\p{Script=Bengali}/u },
  es: { script: latin },
  id: { script: latin },
  it: { script: latin },
  ml: {
    doc: "Surah names in Malayalam: [Latin transliteration, name in Malayalam script].",
    script: /\p{Script=Malayalam}/u
  },
  ms: { script: latin },
  nl: { script: latin },
  sv: { script: latin },
  ur: { script: /\p{Script=Arabic}/u },
  zh: { script: /\p{Script=Han}/u }
}

/** Cyrillic letters in the Italian data and the accented letters they stand for */
const italianRepairs: Record<string, string> = { р: "à", т: "â", ш: "è", ь: "ì", ю: "î", ђ: "ò", ћ: "û" }

interface Chapter {
  id: number
  name_simple: string
  translated_name: { language_name: string; name: string }
}

type Pair = [string, string]

async function fetchNames(lang: string, config: LanguageConfig): Promise<Pair[]> {
  const url = `https://api.quran.com/api/v4/chapters?language=${lang}`
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`${url}: HTTP ${res.status}`)
  }
  const { chapters } = (await res.json()) as { chapters: Chapter[] }
  if (chapters.length !== 114 || chapters.some((c, i) => c.id !== i + 1)) {
    throw new Error(`expected chapters 1..114, got ${chapters.length}`)
  }

  const problems: string[] = []
  const pairs = chapters.map((c): Pair => {
    let name = c.translated_name.name.replaceAll(/\s+/g, " ").trim()
    if (lang === "it") {
      name = name.replaceAll(/[ртшьюђћ]/g, (ch) => italianRepairs[ch])
    }
    if (c.translated_name.language_name === "english") {
      problems.push(`${c.id}: falls back to English "${name}"`)
    } else if (name.match(/\p{L}/gu)?.some((ch) => !config.script.test(ch))) {
      problems.push(`${c.id}: unexpected script in "${name}"`)
    }
    return [c.name_simple.trim(), name]
  })
  if (problems.length > 0) {
    throw new Error(`\n  ${problems.join("\n  ")}`)
  }
  return pairs
}

function exportName(lang: string): string {
  return `surahNames${lang[0].toUpperCase()}${lang.slice(1)}`
}

function renderModule(lang: string, config: LanguageConfig, pairs: Pair[]): string {
  const rows = pairs.map(([name, translation]) => `  [${JSON.stringify(name)}, ${JSON.stringify(translation)}],`)
  return [
    `// Generated by ${scriptRef} from the Quran.com API.`,
    `import type { SurahNames } from "./types"`,
    ``,
    ...(config.doc ? [`/**`, ` * ${config.doc}`, ` */`] : []),
    `export const ${exportName(lang)}: SurahNames = [`,
    `  [],`,
    ...rows,
    `  []`,
    `]`,
    ``
  ].join("\n")
}

async function checkAgainstExisting(lang: string, pairs: Pair[]): Promise<number> {
  const existing = ((await import(join(i18nDir, `surah.${lang}.ts`))) as Record<string, unknown[]>)[exportName(lang)]
  if (!existing) {
    console.error(`  ${exportName(lang)} export not found in src/i18n/surah.${lang}.ts`)
    return 1
  }
  let mismatches = 0
  pairs.forEach((pair, i) => {
    const old = JSON.stringify(existing[i + 1])
    if (JSON.stringify(pair) !== old) {
      console.error(`  ${i + 1}: generated ${JSON.stringify(pair)}, existing ${old}`)
      mismatches++
    }
  })
  return mismatches
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const flags = new Set(args.filter((a) => a.startsWith("--")))
  const requested = args.filter((a) => !a.startsWith("--"))
  const unknown = [...[...flags].filter((f) => f !== "--check"), ...requested.filter((l) => !(l in languages))]
  if (unknown.length > 0) {
    console.error(`Unknown arguments: ${unknown.join(", ")}`)
    console.error(`Usage: pnpx jiti ${scriptRef} [lang...] [--check]`)
    console.error(`Languages: ${Object.keys(languages).join(", ")}`)
    process.exitCode = 1
    return
  }

  let failures = 0
  for (const lang of requested.length > 0 ? requested : Object.keys(languages)) {
    const config = languages[lang]
    const outFile = join(i18nDir, `surah.${lang}.ts`)
    let pairs: Pair[]
    try {
      // oxlint-disable-next-line eslint/no-await-in-loop -- sequential by design, so per-language console output stays in order
      pairs = await fetchNames(lang, config)
    } catch (error) {
      console.error(`✗ ${lang}: ${error instanceof Error ? error.message : String(error)}`)
      failures++
      continue
    }

    if (flags.has("--check")) {
      if (!existsSync(outFile)) {
        console.error(`✗ ${lang}: src/i18n/surah.${lang}.ts does not exist`)
        failures++
        continue
      }
      // oxlint-disable-next-line eslint/no-await-in-loop -- sequential by design, see above
      const mismatches = await checkAgainstExisting(lang, pairs)
      if (mismatches > 0) {
        console.error(`✗ ${lang}: ${mismatches} mismatches against src/i18n/surah.${lang}.ts`)
        failures++
      } else {
        console.error(`✓ ${lang}: matches src/i18n/surah.${lang}.ts`)
      }
      continue
    }

    writeFileSync(outFile, renderModule(lang, config, pairs))
    execSync(`pnpm exec oxfmt "${outFile}"`, { stdio: "ignore" })
    console.error(`Wrote src/i18n/surah.${lang}.ts`)
  }

  if (failures > 0) {
    process.exitCode = 1
  }
}

await main()
