// Generated by scripts/generate-entries.ts - do not edit by hand.

/**
 * Hafs (from 'Asim) entry point.
 *
 * The functional API with the Hafs data already bound, so there is no `lists`
 * argument to pass. Everything is tree-shakeable.
 *
 * @example
 * ```typescript
 * import { meta, findJuz, getAyahMeta, quran } from "quran-meta/hafs"
 *
 * meta.numAyahs // 6236
 * findJuz(2, 142)
 * getAyahMeta(1)
 * quran.getSurahMeta(2) // class-based API
 * ```
 *
 * @module
 */

import { HafsLists } from "./lists/HafsLists"
import type { PartBlock } from "./lists/getList"
import type { PartType, RiwayaName } from "./lists/types"
import type { AyahStepOptions } from "./nextAyah"
import type {
  AyahId,
  AyahMeta,
  AyahNo,
  AyahRange,
  HizbId,
  Juz,
  JuzAndShift,
  JuzMeta,
  Manzil,
  ManzilMeta,
  Page,
  PageMeta,
  QuranMeta,
  RangeMode,
  RubAlHizb,
  RubAlHizbId,
  RubAlHizbMeta,
  Ruku,
  RukuMeta,
  Surah,
  SurahAyah,
  SurahAyahSegment,
  SurahInfo,
  SurahJuzMeta,
  SurahListType,
  SurahMeta
} from "./types"
import { QuranRiwaya } from "./QuranRiwaya"
import { convertAyah as _convertAyah, convertAyahSpan as _convertAyahSpan } from "./convert/convertAyah"
import { nextAyah as _nextAyah } from "./nextAyah"
import { prevAyah as _prevAyah } from "./prevAyah"
import {
  getPartRange as _getPartRange,
  ayahsInPart as _ayahsInPart,
  ayahsInPage as _ayahsInPage,
  ayahsInJuz as _ayahsInJuz
} from "./ayahsInPart"
import { ayahStringSplitter as _ayahStringSplitter } from "./ayahStringSplitter"
import { findAyahIdBySurah as _findAyahIdBySurah } from "./findAyahIdBySurah"
import { findJuz as _findJuz } from "./findJuz"
import {
  findJuzAndShift as _findJuzAndShift,
  findJuzAndShiftByAyahId as _findJuzAndShiftByAyahId
} from "./findJuzAndShift"
import { findJuzByAyahId as _findJuzByAyahId } from "./findJuzByAyahId"
import { findJuzMetaBySurah as _findJuzMetaBySurah } from "./findJuzMetaBySurah"
import { findManzil as _findManzil } from "./findManzil"
import { findManzilByAyahId as _findManzilByAyahId } from "./findManzilByAyahId"
import { findPage as _findPage } from "./findPage"
import { findPagebyAyahId as _findPagebyAyahId } from "./findPagebyAyahId"
import { findRangeAroundAyah as _findRangeAroundAyah } from "./findRangeAroundAyah"
import { findRangeAroundSurahAyah as _findRangeAroundSurahAyah } from "./findRangeAroundSurahAyah"
import { findRubAlHizb as _findRubAlHizb } from "./findRubAlHizb"
import { findRubAlHizbByAyahId as _findRubAlHizbByAyahId } from "./findRubAlHizbByAyahId"
import { findRukuByAyahId as _findRukuByAyahId } from "./findRukuByAyahId"
import { findSurahAyahByAyahId as _findSurahAyahByAyahId } from "./findSurahAyahByAyahId"
import { findSurahByAyahId as _findSurahByAyahId } from "./findSurahByAyahId"
import { formatAyahId as _formatAyahId } from "./formatSurahAyah"
import { getAyahCountInSurah as _getAyahCountInSurah } from "./getAyahCountInSurah"
import { getAyahMeta as _getAyahMeta } from "./getAyahMeta"
import { getAyahMetasForSurah as _getAyahMetasForSurah } from "./getAyahMetasForSurah"
import { getJuzMeta as _getJuzMeta } from "./getJuzMeta"
import { getManzilMeta as _getManzilMeta } from "./getManzilMeta"
import { getPageMeta as _getPageMeta } from "./getPageMeta"
import { getRubAlHizbByAyahId as _getRubAlHizbByAyahId } from "./getRubAlHizbByAyahId"
import { getRubAlHizbMeta as _getRubAlHizbMeta } from "./getRubAlHizbMeta"
import { getRubAlHizbMetaByAyahId as _getRubAlHizbMetaByAyahId } from "./getRubAlHizbMetaByAyahId"
import { getRukuMeta as _getRukuMeta } from "./getRukuMeta"
import { getSurahInfo as _getSurahInfo } from "./getSurahInfo"
import { getSurahMeta as _getSurahMeta } from "./getSurahMeta"
import { isAyahJuzFirst as _isAyahJuzFirst } from "./isAyahJuzFirst"
import { isAyahPageFirst as _isAyahPageFirst } from "./isAyahPageFirst"
import { isSurahAyahJuzFirst as _isSurahAyahJuzFirst } from "./isSurahAyahJuzFirst"
import { isSurahAyahPageFirst as _isSurahAyahPageFirst } from "./isSurahAyahPageFirst"
import {
  getList as _getList,
  getListNormalised as _getListNormalised,
  generatePartBlocks as _generatePartBlocks
} from "./lists/getList"
import { surahStringParser as _surahStringParser } from "./surahStringParser"
import {
  isValidSurah as _isValidSurah,
  isValidAyahId as _isValidAyahId,
  isValidSurahAyah as _isValidSurahAyah,
  isValidPage as _isValidPage,
  isValidJuz as _isValidJuz,
  isValidManzil as _isValidManzil,
  isValidRuku as _isValidRuku,
  isValidHizb as _isValidHizb,
  isValidRubAlHizb as _isValidRubAlHizb
} from "./typeGuards"
import {
  checkValidSurahAyah as _checkValidSurahAyah,
  checkValidSurahAyahPair as _checkValidSurahAyahPair,
  checkValidSurah as _checkValidSurah,
  checkValidAyahId as _checkValidAyahId,
  checkValidPage as _checkValidPage,
  checkValidJuz as _checkValidJuz,
  checkValidRuku as _checkValidRuku,
  checkValidManzil as _checkValidManzil
} from "./validation"

export type * from "./types"
export type { AyahStepOptions } from "./nextAyah"
export type { PartBlock } from "./lists/getList"
export type { PartType, RiwayaName } from "./lists/types"
export { getRubAlHizb } from "./getRubAlHizb"
export { isValidAyahNo } from "./typeGuards"
export { string2NumberSplitter, string2NumberSplitterStrict } from "./ayahStringSplitter"
export { formatSurahAyah } from "./formatSurahAyah"
export { HafsLists } from "./lists/HafsLists"

/** Hafs metadata: number of ayahs, pages, juzs, ... */
export const meta: QuranMeta = HafsLists.meta

export const HizbQuarterList: AyahId[] = HafsLists.HizbQuarterList
export const JuzList: AyahId[] = HafsLists.JuzList
export const ManzilList: AyahId[] = HafsLists.ManzilList
export const PageList: AyahId[] = HafsLists.PageList
export const RukuList: AyahId[] = HafsLists.RukuList
export const SajdaList: AyahId[] = HafsLists.SajdaList
export const SurahList: SurahListType = HafsLists.SurahList

// ==================== Lists and parsing ====================

/** Returns the raw boundary list for a kind of part */
export function getList(listName: PartType): AyahId[] | SurahListType {
  return _getList(listName, HafsLists)
}

/** Returns the parts of a kind as `{ startAyahId, ayahCount }` blocks */
export function getListNormalised(listName: PartType): PartBlock[] {
  return _getListNormalised(listName, HafsLists)
}

/** Like getListNormalised, but returns `null` when the riwaya has no such data */
export function generatePartBlocks(part: PartType): PartBlock[] | null {
  return _generatePartBlocks(part, HafsLists)
}

/** Parses `"2:255"` or `"1:1-7"` into `[surah, ayah]` or `[surah, [from, to]]` */
export function ayahStringSplitter(str: string, isStrict = true): SurahAyahSegment {
  return _ayahStringSplitter(str, isStrict, HafsLists)
}

/** Parses a surah number from a string like `"2"` */
export function surahStringParser(str: string, isStrict = false): Surah {
  return _surahStringParser(str, isStrict, meta)
}

/** Formats an ayah id as `"surah:ayah"` */
export function formatAyahId(ayahId: AyahId): string {
  return _formatAyahId(ayahId, HafsLists)
}

// ==================== Validation ====================

/** Throws unless surah and ayah form a valid reference */
export function checkValidSurahAyah(surah: unknown, ayah: unknown): asserts ayah is AyahNo {
  _checkValidSurahAyah(surah, ayah, HafsLists)
}

/** Throws unless `[surah, ayah]` is a valid reference */
export function checkValidSurahAyahPair(pair: [unknown, unknown]): asserts pair is SurahAyah {
  _checkValidSurahAyahPair(pair, HafsLists)
}

/** Throws unless the value is a valid surah number */
export function checkValidSurah(surah: unknown): asserts surah is Surah {
  _checkValidSurah(surah, meta)
}

/** Throws unless the value is a valid ayah id */
export function checkValidAyahId(ayahId: unknown): asserts ayahId is AyahId {
  _checkValidAyahId(ayahId, meta)
}

/** Throws unless the value is a valid page number */
export function checkValidPage(page: unknown): asserts page is Page {
  _checkValidPage(page, meta)
}

/** Throws unless the value is a valid juz number */
export function checkValidJuz(juz: unknown): asserts juz is Juz {
  _checkValidJuz(juz, meta)
}

/** Throws unless the value is a valid ruku number */
export function checkValidRuku(ruku: unknown): asserts ruku is Ruku {
  _checkValidRuku(ruku, meta)
}

/** Throws unless the value is a valid manzil number */
export function checkValidManzil(manzil: unknown): asserts manzil is Manzil {
  _checkValidManzil(manzil, meta)
}

/** Checks whether the value is a valid surah number */
export function isValidSurah(x: unknown): x is Surah {
  return _isValidSurah(x, meta)
}

/** Checks whether the value is a valid ayah id */
export function isValidAyahId(x: unknown): x is AyahId {
  return _isValidAyahId(x, meta)
}

/** Checks whether `[surah, ayah]` is a valid reference */
export function isValidSurahAyah(x: [unknown, unknown]): x is SurahAyah {
  return _isValidSurahAyah(x, HafsLists)
}

/** Checks whether the value is a valid page number */
export function isValidPage(x: unknown): x is Page {
  return _isValidPage(x, meta)
}

/** Checks whether the value is a valid juz number */
export function isValidJuz(x: unknown): x is Juz {
  return _isValidJuz(x, meta)
}

/** Checks whether the value is a valid manzil number */
export function isValidManzil(x: unknown): x is Manzil {
  return _isValidManzil(x, meta)
}

/** Checks whether the value is a valid ruku number */
export function isValidRuku(x: unknown): x is Ruku {
  return _isValidRuku(x, meta)
}

/** Checks whether the value is a valid hizb number */
export function isValidHizb(x: unknown): x is HizbId {
  return _isValidHizb(x, meta)
}

/** Checks whether the value is a valid rub' al-hizb number */
export function isValidRubAlHizb(x: unknown): x is RubAlHizbId {
  return _isValidRubAlHizb(x, HafsLists)
}

// ==================== Surah and ayah ====================

/** Returns the metadata of a surah */
export function getSurahMeta(surah: Surah): SurahMeta {
  return _getSurahMeta(surah, HafsLists)
}

/** Returns `[firstAyahId, ayahCount, surahOrder, rukuCount, name, isMeccan]` for a surah */
export function getSurahInfo(surah: Surah): SurahInfo {
  return _getSurahInfo(surah, HafsLists)
}

/** Returns the number of ayahs in a surah */
export function getAyahCountInSurah(surah: Surah): AyahNo {
  return _getAyahCountInSurah(surah, HafsLists)
}

/** Converts `surah:ayah` to an ayah id */
export function findAyahIdBySurah(surah: Surah, ayah: AyahNo = 1): AyahId {
  return _findAyahIdBySurah(surah, ayah, HafsLists)
}

/** Returns the surah an ayah id belongs to */
export function findSurahByAyahId(ayahId: AyahId): Surah {
  return _findSurahByAyahId(ayahId, HafsLists)
}

/** Converts an ayah id to `[surah, ayah]` */
export function findSurahAyahByAyahId(ayahId: AyahId): SurahAyah {
  return _findSurahAyahByAyahId(ayahId, HafsLists)
}

/** Returns everything known about an ayah: juz, page, ruku, sajdah, ... */
export function getAyahMeta(ayahId: AyahId): AyahMeta {
  return _getAyahMeta(ayahId, HafsLists)
}

/** Returns getAyahMeta for every ayah of a surah */
export function getAyahMetasForSurah(surah: Surah): AyahMeta[] {
  return _getAyahMetasForSurah(surah, HafsLists)
}

// ==================== Juz ====================

/** Returns the juz of `surah:ayah` */
export function findJuz(surah: Surah, ayah: AyahNo = 1): Juz {
  return _findJuz(surah, ayah, HafsLists)
}

/** Returns the juz of an ayah id */
export function findJuzByAyahId(ayahId: AyahId): Juz {
  return _findJuzByAyahId(ayahId, HafsLists)
}

/** Returns the first and last ayah of a juz */
export function getJuzMeta(juz: Juz): JuzMeta {
  return _getJuzMeta(juz, HafsLists)
}

/** Returns the juz boundaries around `surah:ayah` */
export function findJuzMetaBySurah(surah: Surah, ayah: AyahNo = 1): SurahJuzMeta {
  return _findJuzMetaBySurah(surah, ayah, HafsLists)
}

/** Returns the juz of `surah:ayah` and the distance from the juz start to the surah start */
export function findJuzAndShift(surah: Surah, ayah: AyahNo = 1): JuzAndShift {
  return _findJuzAndShift(surah, ayah, HafsLists)
}

/** Like findJuzAndShift, for an ayah id */
export function findJuzAndShiftByAyahId(ayahId: AyahId): JuzAndShift {
  return _findJuzAndShiftByAyahId(ayahId, HafsLists)
}

// ==================== Page ====================

/** Returns the mushaf page of `surah:ayah` */
export function findPage(surah: Surah, ayah: AyahNo = 1): Page {
  return _findPage(surah, ayah, HafsLists)
}

/** Returns the mushaf page of an ayah id */
export function findPagebyAyahId(ayahId: AyahId): Page {
  return _findPagebyAyahId(ayahId, HafsLists)
}

/** Returns the first and last ayah of a page */
export function getPageMeta(page: Page): PageMeta {
  return _getPageMeta(page, HafsLists)
}

// ==================== Manzil and ruku ====================

/** Returns the manzil of `surah:ayah` */
export function findManzil(surah: Surah, ayah: AyahNo = 1): Manzil {
  return _findManzil(surah, ayah, HafsLists)
}

/** Returns the manzil of an ayah id */
export function findManzilByAyahId(ayahId: AyahId): Manzil {
  return _findManzilByAyahId(ayahId, HafsLists)
}

/** Returns the first and last ayah of a manzil */
export function getManzilMeta(manzil: Manzil): ManzilMeta {
  return _getManzilMeta(manzil, HafsLists)
}

/** Returns the ruku of an ayah id */
export function findRukuByAyahId(ayahId: AyahId): Ruku {
  return _findRukuByAyahId(ayahId, HafsLists)
}

/** Returns the first and last ayah of a ruku */
export function getRukuMeta(ruku: Ruku): RukuMeta {
  return _getRukuMeta(ruku, HafsLists)
}

// ==================== Rub' al-hizb ====================

/** Returns the rub' al-hizb (quarter) of `surah:ayah` */
export function findRubAlHizb(surah: Surah, ayah: AyahNo = 1): RubAlHizbId {
  return _findRubAlHizb(surah, ayah, HafsLists)
}

/** Returns the rub' al-hizb (quarter) of an ayah id */
export function findRubAlHizbByAyahId(ayahId: AyahId): RubAlHizbId {
  return _findRubAlHizbByAyahId(ayahId, HafsLists)
}

/** Returns juz, hizb and quarter numbers of an ayah id */
export function getRubAlHizbByAyahId(ayahId: AyahId): RubAlHizb {
  return _getRubAlHizbByAyahId(ayahId, HafsLists)
}

/** Returns the first and last ayah of a rub' al-hizb */
export function getRubAlHizbMeta(quarterIndex: RubAlHizbId): RubAlHizbMeta {
  return _getRubAlHizbMeta(quarterIndex, HafsLists)
}

/** Returns the rub' al-hizb containing an ayah id, with its first and last ayah */
export function getRubAlHizbMetaByAyahId(ayahId: AyahId): RubAlHizbMeta {
  return _getRubAlHizbMetaByAyahId(ayahId, HafsLists)
}

// ==================== Ranges and iteration ====================

/** Returns the ayah range of the juz/page/surah/... around an ayah id */
export function findRangeAroundAyah(ayahId: AyahId, mode: RangeMode): AyahRange {
  return _findRangeAroundAyah(ayahId, mode, HafsLists)
}

/** Returns the ayah range of the juz/page/surah/... around `surah:ayah` */
export function findRangeAroundSurahAyah(surah: Surah, ayah: AyahNo, mode: RangeMode): AyahRange {
  return _findRangeAroundSurahAyah(surah, ayah, mode, HafsLists)
}

/** Returns `[firstAyahId, lastAyahId]` of a surah, juz, page, manzil, ruku or hizb part */
export function getPartRange(type: PartType, num: number): AyahRange {
  return _getPartRange(type, num, HafsLists)
}

/** Iterates over every `[surah, ayah]` in a part of the Quran */
export function ayahsInPart(type: PartType, num: number): Generator<SurahAyah, void, undefined> {
  return _ayahsInPart(type, num, HafsLists)
}

/** Iterates over every `[surah, ayah]` on a page */
export function ayahsInPage(page: Page): Generator<SurahAyah, void, undefined> {
  return _ayahsInPage(page, HafsLists)
}

/** Iterates over every `[surah, ayah]` in a juz */
export function ayahsInJuz(juz: Juz): Generator<SurahAyah, void, undefined> {
  return _ayahsInJuz(juz, HafsLists)
}

/** Returns the juz number if the ayah id starts a juz, a negative number otherwise */
export function isAyahJuzFirst(ayahId: AyahId): number {
  return _isAyahJuzFirst(ayahId, HafsLists)
}

/** Returns the page number if the ayah id starts a page, a negative number otherwise */
export function isAyahPageFirst(ayahId: AyahId): number {
  return _isAyahPageFirst(ayahId, HafsLists)
}

/** Returns the juz number if `surah:ayah` starts a juz, a negative number otherwise */
export function isSurahAyahJuzFirst(surah: Surah, ayah: AyahNo): number {
  return _isSurahAyahJuzFirst(surah, ayah, HafsLists)
}

/** Returns the page number if `surah:ayah` starts a page, a negative number otherwise */
export function isSurahAyahPageFirst(surah: Surah, ayah: AyahNo): number {
  return _isSurahAyahPageFirst(surah, ayah, HafsLists)
}

// ==================== Navigation ====================

/**
 * Returns the ayah after `surah:ayah`. Wraps from the last ayah to 1:1 unless
 * `{ wrap: false }` is passed, in which case it returns `undefined` there.
 */
export function nextAyah(surah: Surah, ayah: AyahNo, options?: { wrap?: true }): SurahAyah
export function nextAyah(surah: Surah, ayah: AyahNo, options: AyahStepOptions): SurahAyah | undefined
export function nextAyah(surah: Surah, ayah: AyahNo, options: AyahStepOptions = {}): SurahAyah | undefined {
  return _nextAyah(surah, ayah, HafsLists, options)
}

/**
 * Returns the ayah before `surah:ayah`. Wraps from 1:1 to the last ayah unless
 * `{ wrap: false }` is passed, in which case it returns `undefined` there.
 */
export function prevAyah(surah: Surah, ayah: AyahNo, options?: { wrap?: true }): SurahAyah
export function prevAyah(surah: Surah, ayah: AyahNo, options: AyahStepOptions): SurahAyah | undefined
export function prevAyah(surah: Surah, ayah: AyahNo, options: AyahStepOptions = {}): SurahAyah | undefined {
  return _prevAyah(surah, ayah, HafsLists, options)
}

/** Converts a Hafs `surah:ayah` to the numbering of another riwaya */
export function convertAyahTo(surah: Surah, ayah: AyahNo, to: RiwayaName): SurahAyah {
  return _convertAyah(surah, ayah, "Hafs", to)
}

/** Converts a Hafs `surah:ayah` to every ayah of another riwaya that shares its text */
export function convertAyahSpanTo(surah: Surah, ayah: AyahNo, to: RiwayaName): SurahAyahSegment {
  return _convertAyahSpan(surah, ayah, "Hafs", to)
}

// ==================== Class-based API ====================

/**
 * Creates a QuranRiwaya instance for Hafs
 */
export function createHafs(): QuranRiwaya<"Hafs"> {
  return QuranRiwaya.create<"Hafs">(HafsLists)
}

/**
 * Pre-initialized QuranRiwaya instance for Hafs
 *
 * @example
 * ```typescript
 * import { quran } from "quran-meta/hafs"
 *
 * quran.getAyahMeta(1)
 * quran.findJuz(2, 142)
 * ```
 */
export const quran: QuranRiwaya<"Hafs"> = /* @__PURE__ */ createHafs()
